{
  description = "Run Kismet in a Nix environment to monitor WLAN traffic";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs = { self, nixpkgs }:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs { inherit system; };
    in
    {
      packages.${system}.kismet-monitor = pkgs.writeShellApplication {
        name = "kismet-monitor";
        runtimeInputs = with pkgs; [
          kismet
          coreutils
          gnugrep
          iproute2
          iw
          util-linux
        ];

        text = ''
          set -euo pipefail

          INTERFACE="''${1:-wlan0}"
          LOG_DIR="''${PWD}/kismet-logs"
          CAPTURE_DIR="''${LOG_DIR}/captures"
          KISMET_HOME="''${LOG_DIR}/.kismet"
          KISMET_CONFIG="''${LOG_DIR}/kismet.conf"

          if [ "$#" -gt 1 ]; then
            printf '%s\n' "Usage: kismet-monitor [interface]" >&2
            exit 2
          fi

          if ! ip link show "$INTERFACE" >/dev/null 2>&1; then
            printf '%s\n' "Wireless interface does not exist: $INTERFACE" >&2
            exit 1
          fi

          if [ "$(id -u)" -ne 0 ]; then
            printf '%s\n' "This tool must be run as root to configure monitor mode." >&2
            exit 1
          fi

          printf '%s\n' "Setting $INTERFACE to monitor mode."
          ip link set "$INTERFACE" down
          iw dev "$INTERFACE" set type monitor
          ip link set "$INTERFACE" up

          if ! iw dev "$INTERFACE" info | grep -q 'type monitor'; then
            printf '%s\n' "Could not confirm monitor mode on $INTERFACE." >&2
            exit 1
          fi

          mkdir -p "$CAPTURE_DIR" "$KISMET_HOME"

          if [ ! -f "$KISMET_CONFIG" ]; then
            cat > "$KISMET_CONFIG" <<EOF
          # Kismet configuration generated by the flake
          # Adjust as needed for your environment and adapter.
          log_prefix=$CAPTURE_DIR
          # Replace the interface below with the monitor-mode interface you want to use.
          ncsource=wlan0:type=rtl433
          EOF
          fi

          printf '%s\n' "Kismet log directory: $LOG_DIR"
          printf '%s\n' "Interface: $INTERFACE"
          printf '%s\n' "Starting Kismet..."
          printf '\n'

          KISMET_HOME="$KISMET_HOME" kismet -c "$INTERFACE" --no-ncsource --log-prefix "$CAPTURE_DIR"
        '';
      };

      apps.${system}.default = {
        type = "app";
        program = "${self.packages.${system}.kismet-monitor}/bin/kismet-monitor";
      };
    };
}
